name: Say hello and goodbye
on:
  push:
    branches:
      - master
jobs:
  hello_world_job:
    runs-on: ubuntu-18.04
    steps:
      - name: Echo the message
        run: echo "Hello javi"

  goodbye_world_job:
    runs-on: ubuntu-18.04
    steps:
      - name: Echo the message
        run: echo "Goodbye javi"
