name: Say hello
on:
    push:
        branches:
            - master
jobs:
    hello_world_jobs:
        runs-on: ubuntu-18.04 #le indicamos la version de jobs
        steps:
            - name: Echo the message
              run: echo "Hello javi"