name: Deployment Pipeline
on:
    push:
        branches: 
            - master
jobs: 
    deployment:
        runs-on: ubuntu-22.04
        steps:
        - name: hacer checkout
          uses: actions/checkout@v4.1.1
          with:
            fetch-depth: 0


        - name: Setup de Node
          uses: actions/setup-node@v4
          with:
            node-version: 16
        - run: npm ci
        - run: npm test

        - name: Instalar dependencias
          run: npm install

        - name: Lint
          run: npm run eslint


         
